version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: taller-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: taller_db
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./Backend
    container_name: taller-backend
    restart: always
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: taller_db
      DB_USER: root
      DB_PASS: ""
    depends_on:
      - db

volumes:
  mysql_data: